# Generated by Django 4.2.30 on 2026-05-20 17:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Опис')),
                ('director', models.CharField(max_length=150, verbose_name='Режисер')),
                ('year', models.PositiveIntegerField(verbose_name='Рік виходу')),
                ('duration', models.PositiveIntegerField(verbose_name='Тривалість (хв)')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна квитка (грн)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='cinema.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name="Ім'я")),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
            ],
            options={
                'verbose_name': 'Підписка на розсилку',
                'verbose_name_plural': 'Підписки на розсилку',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(max_length=50, verbose_name='Зала')),
                ('starts_at', models.DateTimeField(verbose_name='Початок сеансу')),
                ('seats_total', models.PositiveIntegerField(default=100, verbose_name='Місць всього')),
                ('seats_available', models.PositiveIntegerField(default=100, verbose_name='Доступних місць')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.movie', verbose_name='Фільм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеанси',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість квитків')),
                ('status', models.CharField(choices=[('cart', 'В кошику'), ('ordered', 'Замовлено'), ('paid', 'Оплачено'), ('cancelled', 'Скасовано')], default='cart', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума (грн)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cinema.session', verbose_name='Сеанс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('is_used', models.BooleanField(default=False, verbose_name='Використано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Код відновлення паролю',
                'verbose_name_plural': 'Коди відновлення паролю',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оцінка (1-10)')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cinema.movie', verbose_name='Фільм')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Оцінка',
                'verbose_name_plural': 'Оцінки',
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
